# Generated by Django 2.0.2 on 2018-03-20 22:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications_bootstrap', '0005_alter_pdf_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ('title',), 'verbose_name': 'каталог', 'verbose_name_plural': 'каталоги'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-month', '-id'], 'verbose_name': 'публикацию', 'verbose_name_plural': 'публикации'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('order',), 'verbose_name': 'тип', 'verbose_name_plural': 'типы'},
        ),
        migrations.AddField(
            model_name='publication',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
